export const lightColors = {
  primary: '#005ea1',
  primaryContainer: '#2b78bf',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#fdfcff',
  secondary: '#665e41',
  secondaryContainer: '#ebdfba',
  onSecondaryContainer: '#6a6245',
  tertiary: '#18618c',
  tertiaryContainer: '#3a7aa6',
  onTertiaryContainer: '#fcfcff',
  background: '#f7f9fc',
  onBackground: '#191c1e',
  surface: '#f7f9fc',
  surfaceLowest: '#ffffff',
  surfaceContainerLow: '#f2f4f7',
  surfaceContainer: '#eceef1',
  surfaceContainerHigh: '#e6e8eb',
  surfaceContainerHighest: '#e0e3e6',
  onSurface: '#191c1e',
  onSurfaceVariant: '#414751',
  outline: '#717782',
  outlineVariant: '#c1c7d2',
  streakBg: '#FFF3CD',
  streakText: '#D97706',
  error: '#ba1a1a',
};
