import * as SQLite from 'expo-sqlite';
import { importBookAndWords, parseVocabularyJSON } from '../services/wordImportService';

// Sample vocabulary data for testing
const SAMPLE_WORDS = [
  { word: "abandon", phonetic: "/əˈbændən/", meaning: "v. 放弃，抛弃；n. 放纵", example: "He abandoned his wife and children." },
  { word: "abstract", phonetic: "/ˈæbstrækt/", meaning: "adj. 抽象的；n. 摘要", example: "The professor gave an abstract lecture on philosophy." },
  { word: "accommodate", phonetic: "/əˈkɒmədeɪt/", meaning: "v. 容纳；提供住宿；适应", example: "The hotel can accommodate up to 500 guests." },
  { word: "acquire", phonetic: "/əˈkwaɪər/", meaning: "v. 获得，取得", example: "She acquired a new skill through practice." },
  { word: "adequate", phonetic: "/ˈædɪkwət/", meaning: "adj. 充分的，足够的；适当的", example: "The company has adequate resources for the project." },
  { word: "advocate", phonetic: "/ˈædvəkeɪt/", meaning: "v. 提倡，主张；n. 倡导者", example: "She advocates for environmental protection." },
  { word: "allocate", phonetic: "/ˈæləkeɪt/", meaning: "v. 分配，拨出", example: "The government allocated funds for education." },
  { word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", meaning: "adj. 模棱两可的，含糊的", example: "The instructions were ambiguous and confusing." },
  { word: "anticipate", phonetic: "/ænˈtɪsɪpeɪt/", meaning: "v. 预期，期望", example: "We anticipate a significant increase in sales." },
  { word: "apparent", phonetic: "/əˈpærənt/", meaning: "adj. 明显的；表面上的", example: "It was apparent that he was lying." },
  { word: "appreciate", phonetic: "/əˈpriːʃieɪt/", meaning: "v. 欣赏；感激；理解", example: "I really appreciate your help." },
  { word: "approach", phonetic: "/əˈprəʊtʃ/", meaning: "v. 接近；n. 方法，途径", example: "We need a new approach to solve this problem." },
  { word: "appropriate", phonetic: "/əˈprəʊpriət/", meaning: "adj. 适当的，合适的", example: "Please wear appropriate clothing for the event." },
  { word: "arise", phonetic: "/əˈraɪz/", meaning: "v. 出现；产生；起身", example: "Problems may arise during the implementation." },
  { word: "assume", phonetic: "/əˈsjuːm/", meaning: "v. 假定；承担；呈现", example: "I assume you have read the instructions." },
  { word: "authority", phonetic: "/ɔːˈθɒrəti/", meaning: "n. 权威；当局；权力", example: "The authority made a final decision." },
  { word: "benefit", phonetic: "/ˈbenɪfɪt/", meaning: "n. 利益，好处；v. 有益于", example: "Exercise has many health benefits." },
  { word: "capable", phonetic: "/ˈkeɪpəbl/", meaning: "adj. 有能力的，能干的", example: "She is capable of handling the task." },
  { word: "circumstance", phonetic: "/ˈsɜːkəmstəns/", meaning: "n. 环境，情况", example: "Under the circumstances, we had no choice." },
  { word: "commit", phonetic: "/kəˈmɪt/", meaning: "v. 承诺；犯（罪）；投入", example: "He committed himself to finishing the project." },
  { word: "comprehensive", phonetic: "/ˌkɒmprɪˈhensɪv/", meaning: "adj. 全面的，综合的", example: "The report provides a comprehensive analysis." },
  { word: "consequence", phonetic: "/ˈkɒnsɪkwəns/", meaning: "n. 结果，后果", example: "He suffered the consequences of his actions." },
  { word: "considerable", phonetic: "/kənˈsɪdərəbl/", meaning: "adj. 相当大的，重要的", example: "A considerable amount of time was spent on research." },
  { word: "consistent", phonetic: "/kənˈsɪstənt/", meaning: "adj. 一致的，始终如一的", example: "Her work has been consistent throughout the year." },
  { word: "contribute", phonetic: "/kənˈtrɪbjuːt/", meaning: "v. 贡献；投稿；捐助", example: "Everyone should contribute to the community." },
  { word: "controversy", phonetic: "/ˈkɒntrəvɜːsi/", meaning: "n. 争论，争议", example: "The decision sparked a lot of controversy." },
  { word: "convey", phonetic: "/kənˈveɪ/", meaning: "v. 传达，表达；运输", example: "He tried to convey his feelings through art." },
  { word: "decline", phonetic: "/dɪˈklaɪn/", meaning: "v. 下降；拒绝；n. 衰退", example: "Sales have declined by 10% this quarter." },
  { word: "demonstrate", phonetic: "/ˈdemənstreɪt/", meaning: "v. 证明；演示；示威", example: "The experiment demonstrates the theory." },
  { word: "derive", phonetic: "/dɪˈraɪv/", meaning: "v. 源自；获得", example: "The word derives from Latin." },
  { word: "diminish", phonetic: "/dɪˈmɪnɪʃ/", meaning: "v. 减少，缩小", example: "The pain gradually diminished over time." },
  { word: "distinct", phonetic: "/dɪˈstɪŋkt/", meaning: "adj. 明显的；独特的", example: "There are two distinct approaches to the problem." },
  { word: "domestic", phonetic: "/dəˈmestɪk/", meaning: "adj. 国内的；家庭的", example: "Domestic flights are usually cheaper." },
  { word: "elaborate", phonetic: "/ɪˈlæbərət/", meaning: "adj. 精心制作的；v. 详细说明", example: "Could you elaborate on your proposal?" },
  { word: "eliminate", phonetic: "/ɪˈlɪmɪneɪt/", meaning: "v. 消除，排除", example: "We need to eliminate unnecessary costs." },
  { word: "emerge", phonetic: "/ɪˈmɜːdʒ/", meaning: "v. 出现，浮现", example: "New evidence emerged during the investigation." },
  { word: "emphasis", phonetic: "/ˈemfəsɪs/", meaning: "n. 强调，重点", example: "The emphasis should be on quality." },
  { word: "enable", phonetic: "/ɪˈneɪbl/", meaning: "v. 使能够，使可能", example: "Technology enables us to work remotely." },
  { word: "enhance", phonetic: "/ɪnˈhæns/", meaning: "v. 提高，增强", example: "The new software enhances productivity." },
  { word: "enormous", phonetic: "/ɪˈnɔːməs/", meaning: "adj. 巨大的，庞大的", example: "The project requires an enormous investment." },
  { word: "ensure", phonetic: "/ɪnˈʃʊər/", meaning: "v. 确保，保证", example: "Please ensure all documents are complete." },
  { word: "equivalent", phonetic: "/ɪˈkwɪvələnt/", meaning: "adj. 等值的；n. 等价物", example: "One mile is equivalent to 1.6 kilometers." },
  { word: "erode", phonetic: "/ɪˈrəʊd/", meaning: "v. 侵蚀，腐蚀", example: "The cliffs have been eroded by the sea." },
  { word: "establish", phonetic: "/ɪˈstæblɪʃ/", meaning: "v. 建立，设立", example: "The company was established in 1990." },
  { word: "evaluate", phonetic: "/ɪˈvæljueɪt/", meaning: "v. 评估，评价", example: "We need to evaluate the results carefully." },
  { word: "eventually", phonetic: "/ɪˈventʃuəli/", meaning: "adv. 最终，终于", example: "He eventually found a solution." },
  { word: "evident", phonetic: "/ˈevɪdənt/", meaning: "adj. 明显的，显然的", example: "It was evident that the plan had failed." },
  { word: "exceed", phonetic: "/ɪkˈsiːd/", meaning: "v. 超过，超越", example: "Sales exceeded our expectations." },
  { word: "excessive", phonetic: "/ɪkˈsesɪv/", meaning: "adj. 过度的，过分的", example: "Excessive drinking is harmful to health." },
  { word: "exclusive", phonetic: "/ɪkˈskluːsɪv/", meaning: "adj. 独有的；排他的", example: "The club is exclusive to members only." },
  { word: "exhibit", phonetic: "/ɪɡˈzɪbɪt/", meaning: "v. 展示；表现；n. 展览品", example: "The museum exhibits ancient artifacts." },
  { word: "expand", phonetic: "/ɪkˈspænd/", meaning: "v. 扩大，扩展", example: "The company plans to expand internationally." },
  { word: "explicit", phonetic: "/ɪkˈsplɪsɪt/", meaning: "adj. 明确的，清楚的", example: "The instructions were explicit and clear." },
  { word: "exploit", phonetic: "/ɪkˈsplɔɪt/", meaning: "v. 利用；开发；n. 功绩", example: "They exploited the opportunity to grow." },
  { word: "expose", phonetic: "/ɪkˈspəʊz/", meaning: "v. 暴露；揭露", example: "The report exposed corruption in the government." },
  { word: "external", phonetic: "/ɪkˈstɜːnl/", meaning: "adj. 外部的，外面的", example: "External factors can affect the outcome." },
  { word: "facilitate", phonetic: "/fəˈsɪlɪteɪt/", meaning: "v. 促进，使便利", example: "Technology facilitates communication." },
  { word: "factor", phonetic: "/ˈfæktər/", meaning: "n. 因素；v. 把…因素包括进去", example: "Cost is an important factor in the decision." },
  { word: "flexible", phonetic: "/ˈfleksəbl/", meaning: "adj. 灵活的，可变通的", example: "We need a more flexible approach." },
  { word: "fluctuate", phonetic: "/ˈflʌktʃueɪt/", meaning: "v. 波动，起伏", example: "Prices fluctuate throughout the year." },
  { word: "formula", phonetic: "/ˈfɔːmjələ/", meaning: "n. 公式；方案", example: "The mathematical formula is complex." },
  { word: "fundamental", phonetic: "/ˌfʌndəˈmentl/", meaning: "adj. 基本的，根本的", example: "This is a fundamental principle of physics." },
  { word: "generate", phonetic: "/ˈdʒenəreɪt/", meaning: "v. 产生，发生", example: "The wind turbines generate electricity." },
  { word: "genuine", phonetic: "/ˈdʒenjuɪn/", meaning: "adj. 真正的，真实的", example: "She showed genuine concern for others." },
  { word: "guarantee", phonetic: "/ˌɡærənˈtiː/", meaning: "v. 保证；n. 保证书", example: "We guarantee the quality of our products." },
  { word: "hierarchy", phonetic: "/ˈhaɪərɑːki/", meaning: "n. 等级制度，层次结构", example: "The company has a strict hierarchy." },
  { word: "identical", phonetic: "/aɪˈdentɪkl/", meaning: "adj. 完全相同的", example: "The two documents are identical." },
  { word: "identify", phonetic: "/aɪˈdentɪfaɪ/", meaning: "v. 识别，鉴定", example: "Scientists identified a new species." },
  { word: "ignorant", phonetic: "/ˈɪɡnərənt/", meaning: "adj. 无知的，不了解的", example: "He was ignorant of the facts." },
  { word: "illustrate", phonetic: "/ˈɪləstreɪt/", meaning: "v. 说明，阐明", example: "The diagram illustrates the process." },
  { word: "impact", phonetic: "/ˈɪmpækt/", meaning: "n. 影响；冲击", example: "The policy had a significant impact on the economy." },
  { word: "implement", phonetic: "/ˈɪmplɪment/", meaning: "v. 实施，执行", example: "We will implement the new system next month." },
  { word: "implication", phonetic: "/ˌɪmplɪˈkeɪʃn/", meaning: "n. 含义；暗示；影响", example: "The implications of this decision are serious." },
  { word: "impose", phonetic: "/ɪmˈpəʊz/", meaning: "v. 强加；征税", example: "The government imposed new regulations." },
  { word: "incentive", phonetic: "/ɪnˈsentɪv/", meaning: "n. 激励，动机", example: "The bonus serves as an incentive for employees." },
  { word: "incline", phonetic: "/ɪnˈklaɪn/", meaning: "v. 倾向于；n. 斜坡", example: "I'm inclined to agree with you." },
  { word: "indicate", phonetic: "/ˈɪndɪkeɪt/", meaning: "v. 表明，指出", example: "The data indicates a positive trend." },
  { word: "individual", phonetic: "/ˌɪndɪˈvɪdʒuəl/", meaning: "adj. 个人的；n. 个人", example: "Each individual has unique talents." },
  { word: "inevitable", phonetic: "/ɪnˈevɪtəbl/", meaning: "adj. 不可避免的", example: "Change is inevitable in life." },
  { word: "influence", phonetic: "/ˈɪnfluəns/", meaning: "n. 影响；v. 影响", example: "Parents have a strong influence on children." },
  { word: "innovative", phonetic: "/ˈɪnəveɪtɪv/", meaning: "adj. 创新的，革新的", example: "The company is known for its innovative products." },
  { word: "integrate", phonetic: "/ˈɪntɪɡreɪt/", meaning: "v. 整合，融入", example: "We need to integrate new technology into our systems." },
  { word: "integrity", phonetic: "/ɪnˈteɡrəti/", meaning: "n. 正直；完整", example: "He is a man of great integrity." },
  { word: "interact", phonetic: "/ˌɪntərˈækt/", meaning: "v. 互动，相互作用", example: "Students interact with each other in groups." },
  { word: "interpret", phonetic: "/ɪnˈtɜːprɪt/", meaning: "v. 解释；口译", example: "How do you interpret this passage?" },
  { word: "intervene", phonetic: "/ˌɪntəˈviːn/", meaning: "v. 干预，介入", example: "The government intervened in the crisis." },
  { word: "investigate", phonetic: "/ɪnˈvestɪɡeɪt/", meaning: "v. 调查，研究", example: "Police are investigating the incident." },
  { word: "involve", phonetic: "/ɪnˈvɒlv/", meaning: "v. 涉及；包含", example: "The project involves many stakeholders." },
  { word: "isolate", phonetic: "/ˈaɪsəleɪt/", meaning: "v. 隔离，孤立", example: "The patient was isolated to prevent infection." },
  { word: "justify", phonetic: "/ˈdʒʌstɪfaɪ/", meaning: "v. 证明…正当；为…辩护", example: "Can you justify your decision?" },
  { word: "launch", phonetic: "/lɔːntʃ/", meaning: "v. 发射；发起；n. 发行", example: "The company launched a new product." },
  { word: "legitimate", phonetic: "/lɪˈdʒɪtɪmət/", meaning: "adj. 合法的；正当的", example: "He has a legitimate claim to the property." },
  { word: "liberal", phonetic: "/ˈlɪbərəl/", meaning: "adj. 自由的；开明的", example: "She has liberal views on social issues." },
  { word: "maintain", phonetic: "/meɪnˈteɪn/", meaning: "v. 维持；保养；主张", example: "We must maintain high standards." },
  { word: "manipulate", phonetic: "/məˈnɪpjuleɪt/", meaning: "v. 操纵；使用", example: "He tried to manipulate the situation." },
  { word: "mechanism", phonetic: "/ˈmekənɪzəm/", meaning: "n. 机制；机械装置", example: "The brain has a complex mechanism for memory." },
  { word: "modify", phonetic: "/ˈmɒdɪfaɪ/", meaning: "v. 修改，改变", example: "We need to modify the design." },
  { word: "monitor", phonetic: "/ˈmɒnɪtər/", meaning: "v. 监控；n. 显示器", example: "Doctors monitor the patient's condition." },
  { word: "negotiate", phonetic: "/nɪˈɡəʊʃieɪt/", meaning: "v. 谈判，协商", example: "The two parties negotiated a deal." },
  { word: "neutral", phonetic: "/ˈnjuːtrəl/", meaning: "adj. 中立的；中性的", example: "Switzerland remained neutral during the war." },
  { word: "nevertheless", phonetic: "/ˌnevəðəˈles/", meaning: "adv. 然而，不过", example: "It was raining; nevertheless, we went out." },
  { word: "norm", phonetic: "/nɔːm/", meaning: "n. 规范，标准", example: "Working from home has become the norm." },
  { word: "notion", phonetic: "/ˈnəʊʃn/", meaning: "n. 概念，想法", example: "I reject the notion that money equals happiness." },
  { word: "obligation", phonetic: "/ˌɒblɪˈɡeɪʃn/", meaning: "n. 义务，责任", example: "You have an obligation to report the incident." },
  { word: "obtain", phonetic: "/əbˈteɪn/", meaning: "v. 获得，得到", example: "She obtained a degree in engineering." },
  { word: "obvious", phonetic: "/ˈɒbviəs/", meaning: "adj. 明显的，显而易见的", example: "The answer was obvious to everyone." },
  { word: "occupy", phonetic: "/ˈɒkjupaɪ/", meaning: "v. 占据；使忙碌", example: "The building occupies an entire block." },
  { word: "occur", phonetic: "/əˈkɜːr/", meaning: "v. 发生；出现", example: "Accidents occur frequently on this road." },
  { word: "ongoing", phonetic: "/ˈɒnɡəʊɪŋ/", meaning: "adj. 持续的，进行中的", example: "There is an ongoing investigation." },
  { word: "opponent", phonetic: "/əˈpəʊnənt/", meaning: "n. 对手，反对者", example: "She defeated her opponent in the debate." },
  { word: "option", phonetic: "/ˈɒpʃn/", meaning: "n. 选择，选项", example: "We have several options to consider." },
  { word: "orient", phonetic: "/ˈɔːrient/", meaning: "v. 使适应；确定方向", example: "New employees need time to orient themselves." },
  { word: "outcome", phonetic: "/ˈaʊtkʌm/", meaning: "n. 结果，后果", example: "The outcome of the election was surprising." },
  { word: "overall", phonetic: "/ˌəʊvərˈɔːl/", meaning: "adj. 全面的；adv. 总体上", example: "Overall, the project was successful." },
  { word: "overwhelming", phonetic: "/ˌəʊvəˈwelmɪŋ/", meaning: "adj. 压倒性的；势不可挡的", example: "The response was overwhelming." },
  { word: "participate", phonetic: "/pɑːˈtɪsɪpeɪt/", meaning: "v. 参加，参与", example: "All students should participate in the activity." },
  { word: "perceive", phonetic: "/pəˈsiːv/", meaning: "v. 察觉；理解", example: "She perceived a change in his attitude." },
  { word: "perspective", phonetic: "/pəˈspektɪv/", meaning: "n. 观点；视角", example: "Try to see things from a different perspective." },
  { word: "phenomenon", phonetic: "/fɪˈnɒmɪnən/", meaning: "n. 现象", example: "Global warming is a serious phenomenon." },
  { word: "policy", phonetic: "/ˈpɒləsi/", meaning: "n. 政策，方针", example: "The government introduced a new policy." },
  { word: "portion", phonetic: "/ˈpɔːʃn/", meaning: "n. 部分；一份", example: "A large portion of the budget goes to education." },
  { word: "potential", phonetic: "/pəˈtenʃl/", meaning: "adj. 潜在的；n. 潜力", example: "She has great potential as a leader." },
  { word: "precede", phonetic: "/prɪˈsiːd/", meaning: "v. 先于，在…之前", example: "A brief introduction preceded the main lecture." },
  { word: "predominant", phonetic: "/prɪˈdɒmɪnənt/", meaning: "adj. 主要的，占主导地位的", example: "English is the predominant language in business." },
  { word: "presume", phonetic: "/prɪˈzjuːm/", meaning: "v. 假定，推测", example: "I presume you have the necessary qualifications." },
  { word: "previous", phonetic: "/ˈpriːviəs/", meaning: "adj. 先前的，以前的", example: "She had no previous experience in management." },
  { word: "primarily", phonetic: "/praɪˈmerəli/", meaning: "adv. 主要地", example: "The course is primarily for beginners." },
  { word: "principal", phonetic: "/ˈprɪnsəpl/", meaning: "adj. 主要的；n. 校长", example: "The principal spoke at the assembly." },
  { word: "principle", phonetic: "/ˈprɪnsəpl/", meaning: "n. 原则，原理", example: "He acted on principle, not emotion." },
  { word: "prior", phonetic: "/ˈpraɪər/", meaning: "adj. 在前的；优先的", example: "Prior experience is required for this position." },
  { word: "proceed", phonetic: "/prəˈsiːd/", meaning: "v. 继续进行", example: "Please proceed with the next step." },
  { word: "prohibit", phonetic: "/prəˈhɪbɪt/", meaning: "v. 禁止，阻止", example: "Smoking is prohibited in the building." },
  { word: "promote", phonetic: "/prəˈməʊt/", meaning: "v. 促进；提升；推广", example: "The campaign promotes healthy eating." },
  { word: "proportion", phonetic: "/prəˈpɔːʃn/", meaning: "n. 比例；部分", example: "A large proportion of students passed the exam." },
  { word: "prospect", phonetic: "/ˈprɒspekt/", meaning: "n. 前景；可能性", example: "The prospect of success motivates us." },
  { word: "pursue", phonetic: "/pəˈsjuː/", meaning: "v. 追求；从事", example: "She decided to pursue a career in medicine." },
  { word: "qualify", phonetic: "/ˈkwɒlɪfaɪ/", meaning: "v. 使具有资格；限定", example: "You need a degree to qualify for this job." },
  { word: "radical", phonetic: "/ˈrædɪkl/", meaning: "adj. 根本的；激进的", example: "The company underwent radical changes." },
  { word: "random", phonetic: "/ˈrændəm/", meaning: "adj. 随机的，任意的", example: "The sample was selected at random." },
  { word: "range", phonetic: "/reɪndʒ/", meaning: "n. 范围；v. 变化", example: "The hotel offers a range of services." },
  { word: "react", phonetic: "/riˈækt/", meaning: "v. 反应；起化学反应", example: "How did she react to the news?" },
  { word: "recover", phonetic: "/rɪˈkʌvər/", meaning: "v. 恢复；收回", example: "He is recovering from illness." },
  { word: "reform", phonetic: "/rɪˈfɔːm/", meaning: "v./n. 改革，改良", example: "The government plans to reform the education system." },
  { word: "regime", phonetic: "/reɪˈʒiːm/", meaning: "n. 政权；制度", example: "The regime was overthrown in a revolution." },
  { word: "regulate", phonetic: "/ˈreɡjuleɪt/", meaning: "v. 管理，调节", example: "Laws regulate the use of public spaces." },
  { word: "reinforce", phonetic: "/ˌriːɪnˈfɔːs/", meaning: "v. 加强，增援", example: "The evidence reinforces the theory." },
  { word: "reluctant", phonetic: "/rɪˈlʌktənt/", meaning: "adj. 不情愿的，勉强的", example: "He was reluctant to admit his mistake." },
  { word: "rely", phonetic: "/rɪˈlaɪ/", meaning: "v. 依赖，依靠", example: "You can rely on me for support." },
  { word: "remove", phonetic: "/rɪˈmuːv/", meaning: "v. 移除，去掉", example: "Please remove your shoes before entering." },
  { word: "require", phonetic: "/rɪˈkwaɪər/", meaning: "v. 需要；要求", example: "This position requires strong communication skills." },
  { word: "reside", phonetic: "/rɪˈzaɪd/", meaning: "v. 居住", example: "She resides in a small town." },
  { word: "resolve", phonetic: "/rɪˈzɒlv/", meaning: "v. 解决；决心", example: "We must resolve this conflict peacefully." },
  { word: "retain", phonetic: "/rɪˈteɪn/", meaning: "v. 保持；保留", example: "The company retained all its employees." },
  { word: "reveal", phonetic: "/rɪˈviːl/", meaning: "v. 揭示，透露", example: "The investigation revealed surprising facts." },
  { word: "reverse", phonetic: "/rɪˈvɜːs/", meaning: "v. 颠倒；n. 相反", example: "The court reversed the decision." },
  { word: "revolution", phonetic: "/ˌrevəˈluːʃn/", meaning: "n. 革命；旋转", example: "The industrial revolution changed society." },
  { word: "rigid", phonetic: "/ˈrɪdʒɪd/", meaning: "adj. 严格的；僵硬的", example: "The rules are too rigid." },
  { word: "role", phonetic: "/rəʊl/", meaning: "n. 角色；作用", example: "Education plays a vital role in society." },
  { word: "route", phonetic: "/ruːt/", meaning: "n. 路线；途径", example: "We took a different route to avoid traffic." },
  { word: "scenario", phonetic: "/sɪˈnɑːriəʊ/", meaning: "n. 场景；方案", example: "In the worst-case scenario, we lose everything." },
  { word: "scheme", phonetic: "/skiːm/", meaning: "n. 计划；方案", example: "The government launched a new pension scheme." },
  { word: "scope", phonetic: "/skəʊp/", meaning: "n. 范围；机会", example: "The scope of the project is quite large." },
  { word: "seek", phonetic: "/siːk/", meaning: "v. 寻求；探索", example: "She sought advice from a professional." },
  { word: "select", phonetic: "/sɪˈlekt/", meaning: "v. 选择，挑选", example: "Please select your preferred option." },
  { word: "sequence", phonetic: "/ˈsiːkwəns/", meaning: "n. 顺序；序列", example: "Follow the sequence of steps carefully." },
  { word: "shift", phonetic: "/ʃɪft/", meaning: "v. 转移；n. 转变", example: "There has been a shift in public opinion." },
  { word: "significant", phonetic: "/sɪɡˈnɪfɪkənt/", meaning: "adj. 重要的；显著的", example: "This is a significant achievement." },
  { word: "simultaneously", phonetic: "/ˌsɪmlˈteɪniəsli/", meaning: "adv. 同时地", example: "Both events occurred simultaneously." },
  { word: "somewhat", phonetic: "/ˈsʌmwɒt/", meaning: "adv. 有点，稍微", example: "The result was somewhat disappointing." },
  { word: "sophisticated", phonetic: "/səˈfɪstɪkeɪtɪd/", meaning: "adj. 复杂的；老练的", example: "The system uses sophisticated technology." },
  { word: "specify", phonetic: "/ˈspesɪfaɪ/", meaning: "v. 具体说明，指定", example: "Please specify your requirements." },
  { word: "stable", phonetic: "/ˈsteɪbl/", meaning: "adj. 稳定的", example: "The patient is now in stable condition." },
  { word: "statistic", phonetic: "/stəˈtɪstɪk/", meaning: "n. 统计数据", example: "The statistics show a positive trend." },
  { word: "status", phonetic: "/ˈsteɪtəs/", meaning: "n. 地位；状态", example: "What is the current status of the project?" },
  { word: "stimulate", phonetic: "/ˈstɪmjuleɪt/", meaning: "v. 刺激，激发", example: "The policy aims to stimulate economic growth." },
  { word: "strategy", phonetic: "/ˈstrætədʒi/", meaning: "n. 策略，战略", example: "We need a new marketing strategy." },
  { word: "stress", phonetic: "/stres/", meaning: "n. 压力；v. 强调", example: "She is under a lot of stress at work." },
  { word: "structure", phonetic: "/ˈstrʌktʃər/", meaning: "n. 结构；v. 组织", example: "The company has a flat organizational structure." },
  { word: "submit", phonetic: "/səbˈmɪt/", meaning: "v. 提交；服从", example: "Please submit your application by Friday." },
  { word: "subsequent", phonetic: "/ˈsʌbsɪkwənt/", meaning: "adj. 随后的", example: "Subsequent events proved him right." },
  { word: "substantial", phonetic: "/səbˈstænʃl/", meaning: "adj. 大量的；实质的", example: "The project requires substantial funding." },
  { word: "substitute", phonetic: "/ˈsʌbstɪtjuːt/", meaning: "n. 替代品；v. 替代", example: "You can substitute butter with olive oil." },
  { word: "sufficient", phonetic: "/səˈfɪʃnt/", meaning: "adj. 足够的，充分的", example: "We have sufficient evidence to proceed." },
  { word: "summarize", phonetic: "/ˈsʌməraɪz/", meaning: "v. 总结，概括", example: "Please summarize the main points." },
  { word: "supplement", phonetic: "/ˈsʌplɪment/", meaning: "v. 补充；n. 补充物", example: "She takes vitamin supplements daily." },
  { word: "survey", phonetic: "/ˈsɜːveɪ/", meaning: "n. 调查；v. 调查", example: "We conducted a survey of customer satisfaction." },
  { word: "survive", phonetic: "/səˈvaɪv/", meaning: "v. 幸存，生存", example: "Only a few species survived the disaster." },
  { word: "suspend", phonetic: "/səˈspend/", meaning: "v. 暂停；悬挂", example: "The company suspended operations temporarily." },
  { word: "sustain", phonetic: "/səˈsteɪn/", meaning: "v. 维持；遭受", example: "It's hard to sustain growth in a recession." },
  { word: "symbol", phonetic: "/ˈsɪmbl/", meaning: "n. 象征；符号", example: "The dove is a symbol of peace." },
  { word: "target", phonetic: "/ˈtɑːɡɪt/", meaning: "n. 目标；v. 瞄准", example: "We need to reach our sales target." },
  { word: "technique", phonetic: "/tekˈniːk/", meaning: "n. 技术，技巧", example: "She mastered the technique quickly." },
  { word: "temporary", phonetic: "/ˈtemprəri/", meaning: "adj. 暂时的，临时的", example: "This is a temporary solution." },
  { word: "tendency", phonetic: "/ˈtendənsi/", meaning: "n. 趋势，倾向", example: "There is a tendency to overcomplicate things." },
  { word: "terminate", phonetic: "/ˈtɜːmɪneɪt/", meaning: "v. 终止，结束", example: "The contract was terminated early." },
  { word: "theme", phonetic: "/θiːm/", meaning: "n. 主题", example: "The theme of the conference is innovation." },
  { word: "theory", phonetic: "/ˈθɪəri/", meaning: "n. 理论，学说", example: "The theory is supported by evidence." },
  { word: "thereby", phonetic: "/ˌðeəˈbaɪ/", meaning: "adv. 因此，从而", example: "He resigned, thereby avoiding controversy." },
  { word: "thesis", phonetic: "/ˈθiːsɪs/", meaning: "n. 论文；论点", example: "She completed her doctoral thesis." },
  { word: "thorough", phonetic: "/ˈθʌrə/", meaning: "adj. 彻底的，全面的", example: "The investigation was very thorough." },
  { word: "tradition", phonetic: "/trəˈdɪʃn/", meaning: "n. 传统，惯例", example: "It's a family tradition to gather for holidays." },
  { word: "trait", phonetic: "/treɪt/", meaning: "n. 特征，特点", example: "Honesty is an admirable trait." },
  { word: "transform", phonetic: "/trænsˈfɔːm/", meaning: "v. 转变，改造", example: "Technology has transformed our lives." },
  { word: "transmit", phonetic: "/trænzˈmɪt/", meaning: "v. 传输；传播", example: "The disease is transmitted through water." },
  { word: "trend", phonetic: "/trend/", meaning: "n. 趋势，动向", example: "There is a growing trend towards remote work." },
  { word: "trigger", phonetic: "/ˈtrɪɡər/", meaning: "v. 触发；n. 触发因素", example: "The event triggered a chain reaction." },
  { word: "ultimate", phonetic: "/ˈʌltɪmət/", meaning: "adj. 最终的；根本的", example: "The ultimate goal is world peace." },
  { word: "undergo", phonetic: "/ˌʌndəˈɡəʊ/", meaning: "v. 经历，遭受", example: "The patient underwent surgery." },
  { word: "underlie", phonetic: "/ˌʌndəˈlaɪ/", meaning: "v. 构成…的基础", example: "Several factors underlie this decision." },
  { word: "undertake", phonetic: "/ˌʌndəˈteɪk/", meaning: "v. 承担；从事", example: "She undertook the difficult task." },
  { word: "uniform", phonetic: "/ˈjuːnɪfɔːm/", meaning: "adj. 一致的；n. 制服", example: "The standards should be uniform across all departments." },
  { word: "unique", phonetic: "/juːˈniːk/", meaning: "adj. 独特的，唯一的", example: "Each person has a unique fingerprint." },
  { word: "utilize", phonetic: "/ˈjuːtɪlaɪz/", meaning: "v. 利用，使用", example: "We should utilize all available resources." },
  { word: "valid", phonetic: "/ˈvælɪd/", meaning: "adj. 有效的；合理的", example: "Your passport is no longer valid." },
  { word: "vary", phonetic: "/ˈveəri/", meaning: "v. 变化，不同", example: "Prices vary depending on the season." },
  { word: "vehicle", phonetic: "/ˈviːɪkl/", meaning: "n. 车辆；工具", example: "Electric vehicles are becoming more popular." },
  { word: "via", phonetic: "/ˈvaɪə/", meaning: "prep. 通过，经由", example: "We traveled via Paris." },
  { word: "violate", phonetic: "/ˈvaɪəleɪt/", meaning: "v. 违反，侵犯", example: "He violated the terms of the agreement." },
  { word: "virtual", phonetic: "/ˈvɜːtʃuəl/", meaning: "adj. 虚拟的；实质的", example: "Virtual meetings have become common." },
  { word: "visible", phonetic: "/ˈvɪzəbl/", meaning: "adj. 看得见的，明显的", example: "The results are clearly visible." },
  { word: "volume", phonetic: "/ˈvɒljuːm/", meaning: "n. 体积；音量；卷", example: "Sales volume increased by 20%." },
  { word: "voluntary", phonetic: "/ˈvɒləntri/", meaning: "adj. 自愿的，志愿的", example: "Participation is voluntary." },
  { word: "withdraw", phonetic: "/wɪðˈdrɔː/", meaning: "v. 撤回；取款", example: "He decided to withdraw from the competition." },
  { word: "widespread", phonetic: "/ˈwaɪdspred/", meaning: "adj. 广泛的，普遍的", example: "There is widespread support for the proposal." },
  { word: "yield", phonetic: "/jiːld/", meaning: "v. 产出；屈服；n. 产量", example: "The investment yielded high returns." }
];

export async function seedSampleData(db: SQLite.SQLiteDatabase): Promise<void> {
  // Check if data already exists
  const existingBooks = await db.getFirstAsync<{ count: number }>(
    'SELECT COUNT(*) as count FROM books'
  );

  if (existingBooks && existingBooks.count > 0) {
    return; // Data already seeded
  }

  console.log('Seeding sample vocabulary data...');
  await importBookAndWords(
    db,
    'hongbaoshu_kaoyan',
    '红宝书考研英语词汇（乱序版）',
    SAMPLE_WORDS
  );
  console.log(`Seeded ${SAMPLE_WORDS.length} words`);
}
